#line 2 "standard.yy.c"

#line 4 "standard.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 66
#define YY_END_OF_BUFFER 67
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[586] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   67,   62,   65,   62,   62,   50,   62,   62,
       49,   62,   62,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   63,
       62,   62,   62,   62,   64,   62,   62,   33,   62,   32,
       62,   62,   62,   62,   62,   25,   62,   65,   61,   60,
        0,    0,    0,    0,   48,    0,   58,    0,    0,   38,
        0,    0,   36,    0,    0,   40,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,   63,    0,    0,
        0,   64,    0,   33,    0,   32,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   47,
        0,    0,    0,    0,   38,    0,    0,    0,    0,    0,
       40,    0,   26,    0,    0,    0,    0,    0,   28,    0,
        0,   29,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
       30,    0,    0,   44,    0,   46,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   45,    0,    0,   57,    0,    0,
        0,    0,    0,    0,   38,    0,   37,    0,    0,    0,
       40,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   31,    0,    0,    0,    0,    0,   56,    0,
       51,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   55,   52,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   54,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   15,    0,    0,    0,    0,    0,    0,    0,    0,
       14,    0,   43,   42,   53,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   39,   39,    0,    0,   41,   41,
        0,    0,   35,   34,    0,    0,   27,    0,    0,    0,
        0,    0,    0,    8,    0,    0,    0,    0,    0,    0,
        0,    2,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   23,
        0,    0,   59,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    5,    0,    0,    0,    0,
        0,    0,    0,    0,   22,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    6,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,   21,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    7,
       18,    0,    0,   17,    0,    0,   13,    0,    0,    0,
        0,    0,    0,    0,    0,   16,    0,    0,   12,    0,
        9,    0,    1,    0,    0,   20,    0,    0,    0,   11,
        0,    0,    0,   10,    0,    0,    0,    0,    0,    0,
        0,   24,    0,    0,    0,    0,    3,    0,    0,    0,
        0,   19,    0,    4,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,   12,    1,
        1,    1,    1,    1,   13,   13,   14,   13,   13,   13,
       15,   15,   15,   15,   16,   15,   15,   15,   17,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        1,    1,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   15,   28,   29,   30,   31,
       32,   33,   15,   34,   35,   36,   37,   15,   15,   38,
       39,   15,   40,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[42] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    4,    1,    5,
        6,    1,    7,    7,    8,    8,    8,    1,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[649] =
    {   0,
        0,   23,   46,   68,   90,  112,  134,  156,  178,  200,
      212,  223,  226,    0,  241,    0,  264,  286,  308,    0,
      338,    0,  361,  383,  405,  427,  449,  471,  493,  515,
      537,  559,  856,  976,  976,  851,  842,  976,  839,   20,
      829,    0,  812,  819,  809,  815,  791,  809,  785,  798,
      769,  780,  756,    0,  752,    0,  749,  767,  742,  976,
      767,    0,  736,  729,  976,  754,    0,  734,  712,  732,
      710,  730,  708,  728,  706,  976,  705,  976,  976,  976,
        0,   52,  725,   46,  722,  710,  976,  707,  582,  721,
      708,  719,  718,  705,  623,  716,  703,  714,    5,  700,

        0,  699,    0,  698,  709,   28,  696,  976,    0,  678,
      672,  976,    0,  692,  679,  690,  677,  688,  675,  686,
      673,  672,    0,    0,  683,  682,  681,    0,  680,  976,
      668,  661,  677,  676,  675,  644,  673,  641,  670,  669,
      668,  637,  976,  626,    0,  622,    0,  621,  976,  620,
        0,  976,  636,    0,  618,  617,  646,  615,  644,  613,
      612,    0,    0,  641,  643,  642,  638,  636,  618,  614,
      634,  633,  622,  630,  619,  628,  627,  616,  605,    0,
      601,    0,  584,  599,    0,    0,  598,  588,  606,  583,
      976,  575,  590,  976,    0,  604,  601,    0,  599,  599,

      573,  567,    0,  664,  574,  595,  572,    0,  705,  571,
      570,    0,  582,    0,  565,  566,    0,    0,  578,  572,
      585,  563,  558,  542,  976,  569,  568,    0,  567,  566,
      538,   65,  564,  563,  562,  532,  557,  528,  553,  549,
      548,  519,  518,    0,  519,    0,  535,  515,    0,    0,
      516,  533,  976,  529,  529,  512,  534,  534,    0,  527,
      976,  506,   47,  497,  510,  512,  498,  508,  520,  519,
      510,  516,  505,  512,  509,  497,  496,    0,  478,    0,
      481,  493,    0,    0,  492,  487,  471,  473,  474,  494,
      491,    0,  976,  496,  461,  455,  459,  473,  469,  470,

      469,  477,  476,  453,  452,  472,  469,  451,  443,    0,
      430,    0,  435,  436,    0,    0,  431,  444,  433,  424,
      430,  453,  452,    0,  437,   32,  439,  424,  431,  412,
      417,  413,  436,  435,  423,  422,  432,  431,  409,  417,
        0,  976,    0,  402,  400,    0,    0,  398,  398,  407,
      976,  389,  976,  976,  976,  390,  386,  381,   49,  387,
      397,  386,  383,  375,  976,  403,  391,  388,  976,  395,
      369,  382,  976,  976,  370,  369,  976,  378,  380,  362,
      375,  362,  361,  976,  360,  369,  353,  347,  353,  362,
      347,  976,  369,  341,  340,  366,  339,  337,  341,  344,

      349,  326,  329,  336,  322,  331,  315,  328,  315,  324,
      326,  308,  311,  309,  305,  318,  303,  313,  300,  297,
      285,  293,  288,  289,  301,  283,  280,  291,  296,  275,
      286,  281,  289,  288,  277,  287,  281,  284,  279,  976,
      270,  281,  976,  263,  278,  261,  259,  254,  245,  253,
      262,  247,  246,  252,  260,  245,  248,  236,  257,  252,
      248,  239,   46,  240,  239,  976,  226,  233,  226,  225,
      225,  223,  206,  208,  976,  215,  215,  192,  202,  210,
      191,  192,  200,  201,  182,  181,  179,  172,  171,  163,
      173,  176,  163,  976,  178,  177,  168,  164,  174,  170,

      156,  158,  155,  158,  147,  976,  147,  158,  153,  139,
      138,  141,  145,  136,  147,  128,  126,  146,  131,  119,
      131,  133,  113,  126,  117,  120,  119,  126,  129,  976,
      976,  125,  114,  976,  101,  112,  976,  106,   93,    0,
      108,   91,  109,  107,   88,  976,  101,   96,  976,  104,
      976,   84,  976,   94,  101,  976,   88,   75,   89,  976,
       84,   88,   86,  976,   89,   76,   77,   64,   81,   75,
       63,  976,   60,   46,   55,   57,  976,   60,   44,   31,
       45,  976,   20,  976,  976,  746,  752,  755,  759,  763,
      767,  771,  774,  777,  781,  784,  785,  791,  798,  806,

      810,  813,  816,  819,  820,  822,  826,  829,  832,  835,
      838,  839,  841,  847,  850,  853,  856,  859,  860,  864,
      871,  879,  887,  895,  899,  902,  905,  908,  911,  914,
      917,  920,  923,  926,  929,  932,  935,  938,  941,  944,
      947,  950,  953,  956,  959,  962,  965,  968
    } ;

static yyconst flex_int16_t yy_def[649] =
    {   0,
      586,  586,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,    2,   13,   13,   15,  586,  586,   15,   19,
       15,   21,  586,  586,  586,  586,  586,  586,  586,  586,
      586,  586,  585,  585,  585,  585,  585,  585,  585,  587,
      585,  587,   42,  585,   42,  588,  585,  589,  585,  590,
      585,  591,  585,  592,  592,  593,  593,  594,  585,  585,
      585,  595,  595,  585,  585,  585,  596,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      597,  598,  585,  598,  585,  585,  585,   84,  599,  588,
      585,  589,  589,  585,  600,  590,  585,  591,  591,  585,

      601,  585,  602,  585,  594,  594,  585,  585,  603,  585,
      585,  585,  604,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  605,  606,  585,  607,  585,  607,  585,  585,
      585,  585,  585,  588,  588,  585,  589,  585,  585,  590,
      590,  585,  585,  585,  608,  585,  609,  585,  585,  585,
      610,  585,  585,  611,  585,  585,  585,  585,  585,  585,
      585,  612,  613,  585,  614,  614,  585,  585,  585,  585,
      585,  588,  585,  589,  585,  585,  590,  585,  585,  615,
      585,  616,  585,  585,  617,  618,  585,  585,  585,  585,
      585,  585,  585,  585,  619,  585,  585,  620,  585,  585,

      585,  585,  621,  622,  585,  589,  585,  623,  624,  585,
      585,  625,  585,  626,  585,  585,  627,  628,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  629,  585,  585,
      585,  585,  585,  588,  588,  585,  589,  585,  585,  590,
      590,  585,  585,  630,  585,  631,  585,  585,  632,  633,
      585,  585,  585,  585,  585,  585,  585,  585,  634,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  588,
      585,  589,  585,  585,  590,  585,  585,  635,  585,  636,
      585,  585,  637,  638,  585,  585,  585,  585,  585,  585,
      585,  639,  585,  585,  585,  585,  585,  585,  585,  585,

      585,  585,  588,  585,  585,  585,  590,  585,  585,  640,
      585,  641,  585,  585,  642,  643,  585,  585,  585,  585,
      585,  585,  585,  644,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  588,  585,  585,  585,  590,  585,  585,
      645,  585,  646,  585,  585,  647,  648,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  588,  585,  585,  585,  590,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  588,  585,  585,  590,  585,  585,  585,  585,

      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,

      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,    0,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,

      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585
    } ;

static yyconst flex_int16_t yy_nxt[1018] =
    {   0,
      585,   35,   36,  585,   37,   38,  585,  585,   39,   40,
      585,   41,   42,   43,  585,  143,   44,  550,   42,   45,
       42,   42,   42,   42,   35,   36,   81,   37,   38,   82,
       83,   39,   40,  585,   41,   42,   43,  585,  149,   44,
      551,   42,   45,   42,   42,   42,   42,   35,   36,  357,
       37,   38,  585,  585,   39,   46,  585,   41,  124,  125,
      584,  126,  127,  480,  481,  295,  358,  583,   47,   35,
       36,  582,   37,   38,  581,  385,   39,   46,  296,   41,
      386,  387,  580,  579,  263,  578,  577,  264,  576,  575,
       47,   35,   36,  265,   37,   38,  266,  574,   39,   48,

      267,   41,  573,  268,  572,  571,  570,  569,  568,  567,
      566,  565,   49,   35,   36,  564,   37,   38,  563,  562,
       39,   48,  561,   41,  560,  559,  558,  557,  556,  555,
      554,  553,  552,  549,   49,   35,   36,  548,   37,   38,
      547,  546,   39,   50,  545,   41,  544,  543,  542,  541,
      540,  539,  538,  537,  536,  535,   51,   35,   36,  534,
       37,   38,  533,  532,   39,   50,  531,   41,  530,  529,
      528,  527,  526,  525,  524,  523,  522,  521,   51,   35,
       36,  520,   37,   38,  519,  518,   39,   52,  517,   41,
      516,  515,  514,  513,  512,  511,  510,  509,  508,  507,

       53,   35,   36,  506,   37,   38,  505,  504,   39,   52,
      503,   41,  502,   35,   36,  501,   37,   38,  500,  499,
       39,  498,   53,   41,   35,   36,  497,   37,   38,  496,
      495,   39,  494,  493,   41,   54,  492,  491,   54,   54,
      490,  489,   34,  488,   54,   54,   54,   54,   55,   54,
       56,  487,  486,   56,   56,  485,  484,  483,  482,   56,
       56,   56,   56,   57,   56,   35,   36,  479,   37,   38,
      478,  477,   39,   58,  476,   41,  475,  474,  473,  472,
      471,  470,  469,  468,  467,  466,   59,   35,   36,  465,
       37,   38,  464,  463,   39,   58,  462,   41,  461,  460,

      459,  458,  457,  456,  455,  454,  453,  452,   59,   60,
       61,  451,  450,  449,  448,  447,  446,   62,  445,  444,
       62,   62,  443,  442,  441,  440,   63,   62,   62,   62,
       62,   62,  439,  438,  437,  436,  435,  434,   64,   65,
       66,  433,  432,  431,  430,  429,  428,   67,  427,  426,
       67,   67,  425,  424,  423,  422,   67,   67,   67,   67,
       67,   67,   35,   36,  421,   37,   38,  420,  419,   39,
       68,  418,   41,  417,  416,  396,  415,  414,  393,  413,
      412,  411,  410,   69,   35,   36,  409,   37,   38,  408,
      407,   39,   68,  406,   41,  405,  404,  403,  402,  401,

      400,  399,  398,  397,  396,   69,   35,   36,  395,   37,
       38,  394,  393,   39,   70,  392,   41,  391,  390,  389,
      388,  384,  383,  382,  381,  380,  379,   71,   35,   36,
      378,   37,   38,  376,  375,   39,   70,  372,   41,  371,
      370,  369,  368,  367,  366,  365,  364,  363,  362,   71,
       35,   36,  361,   37,   38,  360,  359,   39,   72,  356,
       41,  354,  353,  352,  351,  350,  349,  348,  345,  344,
      342,   73,   35,   36,  340,   37,   38,  339,  338,   39,
       72,  337,   41,  336,  335,  334,  333,  332,  331,  330,
      329,  328,  327,   73,   35,   36,  326,   37,   38,  325,

      323,   39,   74,  322,   41,  321,  320,  319,  318,  317,
      314,  313,  311,  309,  308,   75,   35,   36,  307,   37,
       38,  306,  305,   39,   74,  272,   41,  304,  303,  302,
      301,  300,  299,  298,  297,  294,  293,   75,   35,   36,
      291,   37,   38,  290,  289,   39,   76,  288,   41,  287,
      286,  285,  282,  281,  279,  277,  276,  274,  275,   77,
       35,   36,  274,   37,   38,  273,  272,   39,   76,  271,
       41,  269,  270,  269,  262,  261,  260,  258,  257,  256,
      255,   77,  133,  254,  133,  133,  133,  133,  133,  133,
      133,  134,  133,  133,  253,  252,  251,  248,  247,  133,

      245,  243,  242,  238,  237,  236,  232,  231,  230,  229,
      227,  226,  224,  223,  222,  221,  220,  219,  216,  215,
      213,  133,  133,  139,  211,  139,  139,  139,  139,  139,
      139,  139,  140,  139,  139,  210,  209,  208,  207,  206,
      139,  205,  204,  203,  202,  201,  200,  199,  585,  197,
      196,  193,  192,  191,  190,  189,  188,  187,  152,  184,
      183,  181,  139,  139,  233,  179,  233,  233,  233,  233,
      233,  233,  233,  234,  233,  233,  178,  176,  177,  176,
      175,  233,  174,  173,  171,  172,  171,  170,  169,  168,
      167,  165,  164,  161,  160,  159,  158,  157,  156,  116,

      155,  114,  153,  233,  233,  239,  152,  239,  239,  239,
      239,  239,  239,  239,  240,  239,  239,  150,  105,  148,
      146,  144,  239,   98,  142,  585,  138,  585,  137,  136,
      585,  132,  131,  130,  129,  122,  121,  120,  119,  118,
      117,  116,  115,  114,  239,  239,   34,   34,   34,   34,
       34,   34,   34,   34,   84,  112,   84,   84,   84,   90,
      111,   90,   90,   93,  110,   93,   93,   96,  108,   96,
       96,   99,  107,   99,   99,  101,  105,  101,  103,  104,
      103,  106,  102,  106,  106,  109,  100,  109,  113,   98,
      113,  123,  123,  128,  128,  128,  128,  128,  135,   97,

      135,  135,  135,  135,  135,  135,  141,   95,  141,  141,
      141,  141,  141,  141,  145,   94,  145,  147,   92,  147,
      151,   91,  151,  154,   89,  154,  162,  162,  163,  163,
      166,   88,  166,  180,   87,  180,  182,   86,  182,  185,
       85,  185,  186,   80,  186,  194,  194,  195,  195,  198,
       79,  198,   78,  198,  212,  585,  212,  214,  585,  214,
      217,  585,  217,  218,  585,  218,  225,  225,  228,  585,
      228,  233,  585,  233,  233,  233,  233,  233,  233,  235,
      585,  235,  235,  235,  235,  235,  235,  239,  585,  239,
      239,  239,  239,  239,  239,  241,  585,  241,  241,  241,

      241,  241,  241,  244,  585,  244,  246,  585,  246,  249,
      585,  249,  250,  585,  250,  259,  585,  259,  278,  585,
      278,  280,  585,  280,  283,  585,  283,  284,  585,  284,
      292,  585,  292,  310,  585,  310,  312,  585,  312,  315,
      585,  315,  316,  585,  316,  324,  585,  324,  341,  585,
      341,  343,  585,  343,  346,  585,  346,  347,  585,  347,
      355,  585,  355,  373,  585,  373,  374,  585,  374,  152,
      585,  152,  377,  585,  377,   33,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,

      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585
    } ;

static yyconst flex_int16_t yy_chk[1018] =
    {   0,
        0,    1,    1,    0,    1,    1,   42,    0,    1,    1,
       42,    1,    1,    1,   99,   99,    1,  540,    1,    1,
        1,    1,    1,    1,    2,    2,   40,    2,    2,   40,
       40,    2,    2,    0,    2,    2,    2,  106,  106,    2,
      540,    2,    2,    2,    2,    2,    2,    3,    3,  326,
        3,    3,   84,   84,    3,    3,   84,    3,   82,   82,
      583,   82,   82,  463,  463,  263,  326,  581,    3,    4,
        4,  580,    4,    4,  579,  359,    4,    4,  263,    4,
      359,  359,  578,  576,  232,  575,  574,  232,  573,  571,
        4,    5,    5,  232,    5,    5,  232,  570,    5,    5,

      232,    5,  569,  232,  568,  567,  566,  565,  563,  562,
      561,  559,    5,    6,    6,  558,    6,    6,  557,  555,
        6,    6,  554,    6,  552,  550,  548,  547,  545,  544,
      543,  542,  541,  539,    6,    7,    7,  538,    7,    7,
      536,  535,    7,    7,  533,    7,  532,  529,  528,  527,
      526,  525,  524,  523,  522,  521,    7,    8,    8,  520,
        8,    8,  519,  518,    8,    8,  517,    8,  516,  515,
      514,  513,  512,  511,  510,  509,  508,  507,    8,    9,
        9,  505,    9,    9,  504,  503,    9,    9,  502,    9,
      501,  500,  499,  498,  497,  496,  495,  493,  492,  491,

        9,   10,   10,  490,   10,   10,  489,  488,   10,   10,
      487,   10,  486,   11,   11,  485,   11,   11,  484,  483,
       11,  482,   10,   11,   12,   12,  481,   12,   12,  480,
      479,   12,  478,  477,   12,   13,  476,  474,   13,   13,
      473,  472,   13,  471,   13,   13,   13,   13,   13,   13,
       15,  470,  469,   15,   15,  468,  467,  465,  464,   15,
       15,   15,   15,   15,   15,   17,   17,  462,   17,   17,
      461,  460,   17,   17,  459,   17,  458,  457,  456,  455,
      454,  453,  452,  451,  450,  449,   17,   18,   18,  448,
       18,   18,  447,  446,   18,   18,  445,   18,  444,  442,

      441,  439,  438,  437,  436,  435,  434,  433,   18,   19,
       19,  432,  431,  430,  429,  428,  427,   19,  426,  425,
       19,   19,  424,  423,  422,  421,   19,   19,   19,   19,
       19,   19,  420,  419,  418,  417,  416,  415,   19,   21,
       21,  414,  413,  412,  411,  410,  409,   21,  408,  407,
       21,   21,  406,  405,  404,  403,   21,   21,   21,   21,
       21,   21,   23,   23,  402,   23,   23,  401,  400,   23,
       23,  399,   23,  398,  397,  396,  395,  394,  393,  391,
      390,  389,  388,   23,   24,   24,  387,   24,   24,  386,
      385,   24,   24,  383,   24,  382,  381,  380,  379,  378,

      376,  375,  372,  371,  370,   24,   25,   25,  368,   25,
       25,  367,  366,   25,   25,  364,   25,  363,  362,  361,
      360,  358,  357,  356,  352,  350,  349,   25,   26,   26,
      348,   26,   26,  345,  344,   26,   26,  340,   26,  339,
      338,  337,  336,  335,  334,  333,  332,  331,  330,   26,
       27,   27,  329,   27,   27,  328,  327,   27,   27,  325,
       27,  323,  322,  321,  320,  319,  318,  317,  314,  313,
      311,   27,   28,   28,  309,   28,   28,  308,  307,   28,
       28,  306,   28,  305,  304,  303,  302,  301,  300,  299,
      298,  297,  296,   28,   29,   29,  295,   29,   29,  294,

      291,   29,   29,  290,   29,  289,  288,  287,  286,  285,
      282,  281,  279,  277,  276,   29,   30,   30,  275,   30,
       30,  274,  273,   30,   30,  272,   30,  271,  270,  269,
      268,  267,  266,  265,  264,  262,  260,   30,   31,   31,
      258,   31,   31,  257,  256,   31,   31,  255,   31,  254,
      252,  251,  248,  247,  245,  243,  242,  241,  240,   31,
       32,   32,  239,   32,   32,  238,  237,   32,   32,  236,
       32,  235,  234,  233,  231,  230,  229,  227,  226,  224,
      223,   32,   89,  222,   89,   89,   89,   89,   89,   89,
       89,   89,   89,   89,  221,  220,  219,  216,  215,   89,

      213,  211,  210,  207,  206,  205,  202,  201,  200,  199,
      197,  196,  193,  192,  190,  189,  188,  187,  184,  183,
      181,   89,   89,   95,  179,   95,   95,   95,   95,   95,
       95,   95,   95,   95,   95,  178,  177,  176,  175,  174,
       95,  173,  172,  171,  170,  169,  168,  167,  166,  165,
      164,  161,  160,  159,  158,  157,  156,  155,  153,  150,
      148,  146,   95,   95,  204,  144,  204,  204,  204,  204,
      204,  204,  204,  204,  204,  204,  142,  141,  140,  139,
      138,  204,  137,  136,  135,  134,  133,  132,  131,  129,
      127,  126,  125,  122,  121,  120,  119,  118,  117,  116,

      115,  114,  111,  204,  204,  209,  110,  209,  209,  209,
      209,  209,  209,  209,  209,  209,  209,  107,  105,  104,
      102,  100,  209,   98,   97,   96,   94,   93,   92,   91,
       90,   88,   86,   85,   83,   77,   75,   74,   73,   72,
       71,   70,   69,   68,  209,  209,  586,  586,  586,  586,
      586,  586,  586,  586,  587,   66,  587,  587,  587,  588,
       64,  588,  588,  589,   63,  589,  589,  590,   61,  590,
      590,  591,   59,  591,  591,  592,   58,  592,  593,   57,
      593,  594,   55,  594,  594,  595,   53,  595,  596,   52,
      596,  597,  597,  598,  598,  598,  598,  598,  599,   51,

      599,  599,  599,  599,  599,  599,  600,   50,  600,  600,
      600,  600,  600,  600,  601,   49,  601,  602,   48,  602,
      603,   47,  603,  604,   46,  604,  605,  605,  606,  606,
      607,   45,  607,  608,   44,  608,  609,   43,  609,  610,
       41,  610,  611,   39,  611,  612,  612,  613,  613,  614,
       37,  614,   36,  614,  615,   33,  615,  616,    0,  616,
      617,    0,  617,  618,    0,  618,  619,  619,  620,    0,
      620,  621,    0,  621,  621,  621,  621,  621,  621,  622,
        0,  622,  622,  622,  622,  622,  622,  623,    0,  623,
      623,  623,  623,  623,  623,  624,    0,  624,  624,  624,

      624,  624,  624,  625,    0,  625,  626,    0,  626,  627,
        0,  627,  628,    0,  628,  629,    0,  629,  630,    0,
      630,  631,    0,  631,  632,    0,  632,  633,    0,  633,
      634,    0,  634,  635,    0,  635,  636,    0,  636,  637,
        0,  637,  638,    0,  638,  639,    0,  639,  640,    0,
      640,  641,    0,  641,  642,    0,  642,  643,    0,  643,
      644,    0,  644,  645,    0,  645,  646,    0,  646,  647,
        0,  647,  648,    0,  648,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,

      585,  585,  585,  585,  585,  585,  585,  585,  585,  585,
      585,  585,  585,  585,  585,  585,  585
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.lex"
#line 2 "scanner.lex"
#include <iostream>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <vector>
#include <utility>
#include <cctype>
#include <algorithm>
#include <map>
#include <sstream>
#include <boost/date_time/gregorian/greg_month.hpp>

using namespace std;
using namespace boost::posix_time;
using namespace boost::gregorian;

string Tid; string Date; string Time; string HexId; 
char *pch;
unsigned int bats_counter = 0;

pair<string,string> entry_pair;
extern vector < pair<string,string> >  box_entries; 
extern string Year; //the year of the analysis
extern map<string,string> monaten; //maps months to their numerical value

extern map<string,ptime> box_occupation; //maps box names to their dates of occupation
					 //if a box has not been occupied, this date
					 //is set to not_a_date_time
					 
extern map<string,ptime> box_installation; //maps box names to their dates of installation

/*stores the box programming: box_name->vector of bats programmed for this box*/
extern map<string,vector<string> > box_programming; 

/*stores the occupying bats for each box*/
extern map<string,vector<string> > box_occup_bats;

/*maps box names to box-specific occupation deadline hour*/
extern map<string,string> box_occupation_deadline;

//pair<string,ptime> box_occupation_entry;
string box_name, box_date,current_programmed_box,current_occup_box,box_installation_name,box_installation_date;

extern map<string,unsigned,bool(*)(string,string)> bats_map;
//extern vector<string> bats_vector;
extern vector<string> transponders_vector;
extern time_duration roundtrip_time;
extern time_duration lf_delay;
extern string occupation_deadline;
extern string Year;
extern bool create_sqlitedb;
int comment_caller;









  





#line 954 "standard.yy.c"

#define INITIAL 0
#define BOX_OCCUPATION 1
#define BOX_OCCUPATION_DEADLINE 2
#define BOX_INSTALLATION 3
#define BOX_OCCUP_BATS 4
#define COMMENT 5
#define BATS 6
#define TRANSPONDERS 7
#define BOX_PROGRAMMING 8
#define INSIDE_BOX_PROGRAMMING 9
#define INSIDE_BOX_OCCUP_BATS 10
#define BATUPDATE 11
#define LFDELAY 12
#define OCCUPATIONDEADLINE 13
#define YEAR 14
#define EXPORTDATABASE 15

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 72 "scanner.lex"

#line 1158 "standard.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 586 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 976 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 73 "scanner.lex"
BEGIN(EXPORTDATABASE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 74 "scanner.lex"
BEGIN(YEAR);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 75 "scanner.lex"
BEGIN(OCCUPATIONDEADLINE);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 76 "scanner.lex"
BEGIN(BOX_OCCUPATION_DEADLINE);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 77 "scanner.lex"
BEGIN(LFDELAY);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 78 "scanner.lex"
BEGIN(BATUPDATE);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 79 "scanner.lex"
BEGIN(TRANSPONDERS);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 80 "scanner.lex"
BEGIN(BATS);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 81 "scanner.lex"
BEGIN(BOX_OCCUPATION);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 82 "scanner.lex"
BEGIN(BOX_INSTALLATION);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 83 "scanner.lex"
{current_programmed_box="";BEGIN(BOX_PROGRAMMING);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 84 "scanner.lex"
{current_occup_box="";BEGIN(BOX_OCCUP_BATS);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 85 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 86 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 87 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 88 "scanner.lex"
BEGIN(INITIAL);  
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 89 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 90 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 91 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 93 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 94 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 95 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 96 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 98 "scanner.lex"
{
  string ss;
  pch=strtok(yytext,".");
  ss=pch;
  if (ss == "0") create_sqlitedb=false;
  else if (ss == "1") create_sqlitedb=true;
  else {
    printf("Error: Unrecognized value for exportdatabase in config file\n");
    exit(1);
  }
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 110 "scanner.lex"
{
  pch=strtok(yytext,":");
  current_occup_box = pch;
  BEGIN(INSIDE_BOX_OCCUP_BATS);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 116 "scanner.lex"
{
  pch=strtok(yytext,".");
  string current_occupying_bat = pch;
  if (current_occup_box == "") {
    printf("Error: Something went wrong while processing the box programming from the config file\n");
    exit(1);
  }  
  vector<string> &ref = box_occup_bats[current_occup_box];
  ref.push_back(current_occupying_bat);  
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 127 "scanner.lex"
{
  pch=strtok(yytext,":");
  current_programmed_box = pch;
  BEGIN(INSIDE_BOX_PROGRAMMING);
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 133 "scanner.lex"
{
  pch=strtok(yytext,".");
  string current_programmed_bat = pch;
  if (current_programmed_box == "") {
    printf("Error: Something went wrong while processing the box programming from the config file\n");
    exit(1);
  }  
  vector<string> &ref = box_programming[current_programmed_box];
  ref.push_back(current_programmed_bat);  
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 145 "scanner.lex"
{
  pch=strtok(yytext,".");
  Year = pch;
}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 150 "scanner.lex"
{
  pch=strtok(yytext,".");
  occupation_deadline = pch;
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 155 "scanner.lex"
{
  int digit;
  stringstream ss;
  pch = strtok(yytext,".");
  //printf("%s\n",pch);
  ss<<pch; ss>>digit;
  lf_delay = minutes(digit);
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 165 "scanner.lex"
{
  int digit;
  stringstream ss;
  pch = strtok(yytext,".");
  //printf("%s\n",pch);
  ss<<pch; ss>>digit;
  roundtrip_time = minutes(digit);
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 174 "scanner.lex"
{  
  string transponders_hexid;
  pch = strtok(yytext,".");
  transponders_hexid = pch;
  transponders_vector.push_back(transponders_hexid);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 182 "scanner.lex"
{  
  string bat_hexid;
  pch = strtok(yytext,".");
  bat_hexid = pch;
  bats_map[bat_hexid] = bats_counter++;
  //bats_vector.push_back(bat_hexid);
}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 190 "scanner.lex"
{  
  pch = strtok(yytext,".");
  box_name = pch;  
} 
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 195 "scanner.lex"
{
  pch = strtok(yytext,".");
  string str = pch;
  box_occupation_deadline[box_name] =  str;
}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 203 "scanner.lex"
{  
  pch = strtok(yytext,".");
  box_name = pch;
  //printf("box: %s\n",box_name.c_str());
}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 209 "scanner.lex"
{
  string local_day, local_month, local_year;
  pch = strtok(yytext,".");
  local_day = pch;
  pch = strtok(NULL,".");
  local_month = pch;
  pch = strtok(NULL,".");
  local_year = pch;
  box_date = local_year+local_month+local_day+"T"+occupation_deadline; 
  //printf("Time: %s\n",box_date.c_str());
  ptime occupation_time(from_iso_string(box_date));
  //printf("Time: %s\n",to_simple_string(occupation_time).c_str());
  box_occupation[box_name] =  occupation_time;
}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 224 "scanner.lex"
{  
  pch = strtok(yytext,".");
  box_installation_name = pch;
  //printf("box: %s\n",box_name.c_str());
}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 230 "scanner.lex"
{
  string local_day, local_month, local_year;
  pch = strtok(yytext,".");
  local_day = pch;
  pch = strtok(NULL,".");
  local_month = pch;
  pch = strtok(NULL,".");
  local_year = pch;
  box_installation_date = local_year+local_month+local_day+"T000000"; 
  //printf("Time: %s\n",box_installation_date.c_str());
  ptime installation_time(from_iso_string(box_installation_date));  
  box_installation[box_installation_name] =  installation_time;
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 247 "scanner.lex"
{
  string local_month, local_day, local_year;  
  pch = strtok(yytext,"-");
  local_year = pch;
  pch = strtok(NULL,"-");
  local_month = pch;
  pch = strtok(NULL,"-");
  local_day = pch;  
  Date = local_year + local_month + local_day;//20020131
  //printf("Year: %s ",Date.c_str());  

}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 260 "scanner.lex"
{
  string local_month, local_day, local_year;
  
  pch = strtok(yytext,".");
  local_day = pch;
  pch = strtok(NULL,".");
  local_month = pch;
  pch = strtok(NULL,".");
  local_year = pch;
  
  Date = local_year + local_month + local_day;//20020131
  //printf("Year: %s ",Date.c_str());
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 274 "scanner.lex"
{
  string local_month, local_day="0";
  stringstream ss;
  pch = strtok(yytext,"-");
  local_day += pch;
  pch = strtok(NULL,"-");
  local_month = pch;
  transform(local_month.begin(), local_month.end(),local_month.begin(),::toupper);
  
  ss<<Year<<monaten[local_month]<<local_day;    
  Date = ss.str(); //20080131
  //printf("A date: %s ",Date.c_str());
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 289 "scanner.lex"
{
  string local_month, local_day;
  stringstream ss;
  
  pch = strtok(yytext,"-");
  local_day = pch;
  pch = strtok(NULL,"-");
  local_month = pch;
  transform(local_month.begin(), local_month.end(),local_month.begin(),::toupper);
  
  ss<<Year<<monaten[local_month]<<local_day;    
  Date = ss.str(); //20080131
  //printf("A date: %s ",Date.c_str());
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 306 "scanner.lex"
{
  string local_month, local_day;
  
  pch = strtok(yytext,".");
  local_day = pch;
  pch = strtok(NULL,".");
  local_month = pch;

  Date = Year + local_month + local_day; //20080131
  //printf("A date: %s ",yytext);
}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 321 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 322 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 323 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 324 "scanner.lex"
/*ignore this token*/
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 326 "scanner.lex"
{
  Time="0";
  pch = strtok(yytext,":");
  Time = Time + pch;
  pch = strtok(NULL,":");
  Time += pch;
  pch = strtok(NULL,":");
  Time += pch;

  Date += "T" + Time; //20020131T235959
  //printf("Time: %s\n",Date.c_str());
  
  if (!HexId.empty()) { //Trovan Unique files
    //HexId should've been already scanned
    if (HexId == "000697B587") //this bat was mistakenly recorded in the transponders
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }

}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 353 "scanner.lex"
{
  pch = strtok(yytext,":");
  Time = pch;
  pch = strtok(NULL,":");
  Time += pch;
  pch = strtok(NULL,":");
  Time += pch;

  Date += "T" + Time; //20020131T235959
  //printf("Time: %s\n",Date.c_str());
  
  if (!HexId.empty()) { //Trovan Unique files
    //HexId should've been already scanned
    if (HexId == "000697B587") //this bat was mistakenly recorded in the transponders
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }

}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 378 "scanner.lex"
{
  HexId = yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);
  //cout<<HexId<<endl;
  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 395 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "0";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 415 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "00";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 435 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "000";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 453 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "0000";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 471 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 473 "scanner.lex"
{
  box_entries.pop_back();
  Date = "";
  Time = "";
  HexId = "";
}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 480 "scanner.lex"
{
comment_caller = YY_START;
BEGIN(COMMENT);
}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 484 "scanner.lex"
BEGIN(comment_caller);
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 487 "scanner.lex"
//{printf("%s",yytext);}/* ignore this token in any start condition*/
	YY_BREAK
case 63:
/* rule 63 can match eol */
YY_RULE_SETUP
#line 489 "scanner.lex"
{BEGIN(BOX_PROGRAMMING);}
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 490 "scanner.lex"
{BEGIN(BOX_OCCUP_BATS);}
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 492 "scanner.lex"
//{printf("%s",yytext);}/*ignore this token in any start condition*/
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 494 "scanner.lex"
ECHO;
	YY_BREAK
#line 1873 "standard.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BOX_OCCUPATION):
case YY_STATE_EOF(BOX_OCCUPATION_DEADLINE):
case YY_STATE_EOF(BOX_INSTALLATION):
case YY_STATE_EOF(BOX_OCCUP_BATS):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(BATS):
case YY_STATE_EOF(TRANSPONDERS):
case YY_STATE_EOF(BOX_PROGRAMMING):
case YY_STATE_EOF(INSIDE_BOX_PROGRAMMING):
case YY_STATE_EOF(INSIDE_BOX_OCCUP_BATS):
case YY_STATE_EOF(BATUPDATE):
case YY_STATE_EOF(LFDELAY):
case YY_STATE_EOF(OCCUPATIONDEADLINE):
case YY_STATE_EOF(YEAR):
case YY_STATE_EOF(EXPORTDATABASE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 586 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 586 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 585);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 494 "scanner.lex"





