#line 2 "standard.yy.c"

#line 4 "standard.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 53
#define YY_END_OF_BUFFER 54
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[434] =
    {   0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   54,   50,   52,   50,   50,   38,
       50,   50,   37,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   50,   50,   51,   50,   50,   50,   50,
       25,   50,   24,   50,   50,   50,   50,   50,   19,   50,
       52,   49,   48,    0,    0,    0,    0,   36,    0,   46,
        0,    0,   28,    0,    0,    0,    0,    0,    0,    0,
        0,   51,    0,    0,    0,   25,    0,   24,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,   35,    0,    0,    0,    0,   28,    0,    0,    0,
        0,    0,   20,    0,    0,   21,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   22,    0,    0,   32,
        0,   34,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   33,    0,    0,   45,    0,    0,    0,
        0,    0,    0,   28,    0,    0,    0,    0,    0,    0,
        0,    0,    0,   23,    0,    0,    0,    0,    0,   44,

        0,   39,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,   43,   40,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,   42,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   12,    0,    0,    0,    0,    0,
        0,    0,   11,    0,   31,   30,   41,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   29,   29,    0,   27,
       26,    0,    0,    0,    0,    0,    0,    0,    0,    7,

        0,    0,    0,    0,    0,    0,    2,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   17,    0,    0,   47,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    4,    0,    0,    0,    0,    0,   16,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    5,    0,    0,    0,    0,    0,    0,
       15,    0,    0,    0,    0,    0,    0,    0,    0,    0,

        0,    0,    0,    0,    0,    0,    0,    6,   14,    0,
        0,   10,    0,    0,    0,    0,   13,    0,    8,    0,
        1,    0,    0,    9,    0,    0,    0,    0,    0,   18,
        0,    3,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    3,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    1,    6,    7,    8,    9,   10,   10,   10,
       10,   10,   10,   10,   10,   10,   10,   11,   12,    1,
        1,    1,    1,    1,   13,   13,   14,   13,   13,   13,
       15,   15,   15,   15,   16,   15,   15,   15,   17,   15,
       15,   15,   15,   15,   15,   15,   15,   15,   15,   15,
        1,    1,    1,    1,   18,    1,   19,   20,   21,   22,

       23,   24,   25,   26,   27,   15,   28,   29,   30,   31,
       32,   33,   15,   34,   35,   36,   37,   15,   15,   38,
       39,   15,   40,    1,   41,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[42] =
    {   0,
        1,    2,    1,    1,    1,    1,    3,    4,    1,    5,
        6,    1,    7,    7,    8,    8,    8,    1,    7,    7,
        7,    7,    7,    7,    8,    8,    8,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    1,
        1
    } ;

static yyconst flex_int16_t yy_base[482] =
    {   0,
        0,   23,   46,   68,   80,   91,   94,    0,  109,    0,
      132,  154,  176,    0,  206,  228,  250,  272,  294,  316,
      338,  360,  382,  404,  684,  685,  685,  681,  673,  685,
      676,   20,  668,    0,  653,  662,  654,  666,  643,    0,
      640,    0,  637,  655,  631,  685,  657,    0,  627,  621,
      640,  616,  634,  610,  628,  604,  622,  598,  685,  595,
      685,  685,  685,    0,   52,  613,   46,  608,  589,  685,
      579,  427,  591,  574,    0,  571,    0,  568,  577,    5,
      563,  685,    0,  549,  544,  562,  547,  552,  537,  546,
      526,  528,  512,  509,    0,    0,  518,  514,  509,    0,

      497,  685,  485,  478,  494,  493,  492,  461,    0,  460,
        0,  459,  685,  458,    0,  685,  474,  456,  455,  484,
      453,  482,  451,  450,    0,    0,  479,  481,  480,  475,
      473,  455,  451,  471,  460,  446,    0,  445,    0,  428,
      443,    0,  442,  432,  450,  427,  685,  419,  434,  685,
        0,  448,  445,    0,  443,  443,  417,  411,    0,  468,
      418,    0,  430,    0,  414,  415,    0,  427,  420,  433,
      421,  418,  402,  685,  419,  416,    0,  415,  414,  386,
      129,  412,  411,  410,  381,    0,  382,    0,  398,  377,
        0,  376,  393,  685,  387,  385,  370,  392,  394,    0,

      390,  685,  369,   47,  360,  373,  375,  361,  370,  380,
      379,  368,    0,  347,    0,  350,  362,    0,  361,  356,
      340,  342,  343,  364,  363,    0,  685,  367,  332,  329,
      331,  342,  338,  339,  338,  346,  345,  322,    0,  312,
        0,  317,  318,    0,  312,  323,  312,  301,  304,  327,
      326,    0,  312,   32,  316,  301,  310,  294,  299,  295,
      317,  314,  302,    0,  685,    0,  287,  282,    0,  282,
      285,  294,  685,  276,  685,  685,  685,  277,  273,  268,
        6,  274,  284,  272,  267,  260,  685,  288,  273,  685,
      685,  261,  260,  269,  271,  253,  266,  253,  253,  685,

      264,  249,  244,  250,  257,  239,  685,  261,  233,  238,
      243,  248,  227,  238,  245,  231,  239,  237,  225,  232,
      231,  213,  216,  214,  224,  211,  208,  202,  210,  205,
      205,  217,  198,  207,  209,  188,  199,  194,  205,  200,
      203,  198,  685,  189,  200,  685,  181,  181,  179,  174,
      165,  173,  182,  167,  168,  171,  153,  175,  172,  168,
      169,  168,  166,  685,  153,  160,  155,  146,  150,  685,
      154,  156,  133,  137,  142,  151,  152,  135,  135,  121,
      127,  130,  116,  685,  123,  118,  128,  124,  110,  112,
      685,  109,  120,  113,   95,   99,   90,  101,   80,   79,

       87,   88,   68,   75,   74,   79,   82,  685,  685,   58,
       69,  685,   54,   65,   47,   65,  685,   57,  685,   40,
      685,   47,   44,  685,   45,   45,   34,   23,   38,  685,
        0,  685,  685,  509,  515,  518,  522,  525,  528,  532,
      533,  539,  546,  550,  553,  556,  557,  559,  563,  566,
      569,  572,  573,  575,  581,  584,  587,  590,  591,  595,
      602,  610,  614,  617,  620,  623,  626,  629,  632,  635,
      638,  641,  644,  647,  650,  653,  656,  659,  662,  665,
      668
    } ;

static yyconst flex_int16_t yy_def[482] =
    {   0,
      434,  434,  434,  434,  434,  434,    2,    7,    7,    9,
      434,  434,    9,   13,  434,  434,  434,  434,  434,  434,
      434,  434,  434,  434,  433,  433,  433,  433,  433,  433,
      433,  435,  433,  435,   34,  433,   34,  436,  433,  437,
      437,  438,  438,  439,  433,  433,  433,  440,  440,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  441,  442,  433,  442,  433,  433,  433,
       67,  443,  436,  433,  444,  433,  445,  433,  439,  439,
      433,  433,  446,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  447,  448,  433,  449,  433,  449,

      433,  433,  433,  433,  433,  436,  436,  433,  450,  433,
      451,  433,  433,  433,  452,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  453,  454,  433,  455,  455,  433,
      433,  433,  433,  433,  436,  433,  456,  433,  457,  433,
      433,  458,  433,  433,  433,  433,  433,  433,  433,  433,
      459,  433,  433,  460,  433,  433,  433,  433,  461,  462,
      433,  463,  433,  464,  433,  433,  465,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  466,  433,  433,  433,
      433,  433,  436,  436,  433,  467,  433,  468,  433,  433,
      469,  433,  433,  433,  433,  433,  433,  433,  433,  470,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      436,  433,  471,  433,  472,  433,  433,  473,  433,  433,
      433,  433,  433,  433,  433,  474,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  436,  433,  475,  433,
      476,  433,  433,  477,  433,  433,  433,  433,  433,  433,
      433,  478,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  436,  433,  479,  433,  480,  433,  433,  481,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  436,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  436,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,    0,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433
    } ;

static yyconst flex_int16_t yy_nxt[727] =
    {   0,
      433,   27,   28,  433,   29,   30,  433,  433,   31,   32,
      433,   33,   34,   35,  433,  113,   36,  433,   34,   37,
       34,   34,   34,   34,   27,   28,   64,   29,   30,   65,
       66,   31,   32,  433,   33,   34,   35,  301,  302,   36,
      432,   34,   37,   34,   34,   34,   34,   27,   28,  279,
       29,   30,  433,  433,   31,   38,  433,   33,   96,   97,
      431,   98,   99,  430,  429,  229,  280,  428,   39,   27,
       28,  427,   29,   30,  426,  425,   31,   38,  230,   33,
      424,   27,   28,  423,   29,   30,  422,  421,   31,  420,
       39,   33,   27,   28,  419,   29,   30,  418,  417,   31,

      416,  415,   33,   40,  414,  413,   40,   40,  412,  411,
       26,  410,   40,   40,   40,   40,   41,   40,   42,  409,
      408,   42,   42,  407,  406,  405,  404,   42,   42,   42,
       42,   43,   42,   27,   28,  403,   29,   30,  402,  401,
       31,   44,  400,   33,  399,  398,  397,  396,  204,  395,
      394,  205,  393,  392,   45,   27,   28,  206,   29,   30,
      207,  391,   31,   44,  208,   33,  390,  209,  389,  388,
      387,  386,  385,  384,  383,  382,   45,   46,   47,  381,
      380,  379,  378,  377,  376,   48,  375,  374,   48,   48,
      373,  372,  371,  370,   49,   48,   48,   48,   48,   48,

      369,  368,  367,  366,  365,  364,   50,   27,   28,  363,
       29,   30,  362,  361,   31,   51,  360,   33,  359,  358,
      357,  356,  355,  354,  353,  352,  351,  350,   52,   27,
       28,  349,   29,   30,  348,  347,   31,   51,  346,   33,
      345,  344,  343,  342,  341,  340,  339,  338,  337,  336,
       52,   27,   28,  335,   29,   30,  334,  333,   31,   53,
      332,   33,  331,  330,  329,  328,  327,  326,  325,  324,
      308,  323,   54,   27,   28,  322,   29,   30,  321,  320,
       31,   53,  319,   33,  318,  317,  316,  315,  314,  313,
      312,  311,  310,  309,   54,   27,   28,  308,   29,   30,

      307,  306,   31,   55,  305,   33,  304,  303,  300,  299,
      298,  297,  296,  295,  294,  293,   56,   27,   28,  292,
       29,   30,  289,  288,   31,   55,  287,   33,  286,  285,
      284,  283,  282,  281,  278,  276,  275,  274,   56,   27,
       28,  273,   29,   30,  272,  271,   31,   57,  270,   33,
      268,  267,  265,  263,  262,  261,  260,  259,  258,  257,
       58,   27,   28,  256,   29,   30,  255,  254,   31,   57,
      253,   33,  251,  250,  249,  248,  247,  246,  245,  243,
      242,  240,   58,   27,   28,  238,   29,   30,  237,  236,
       31,   59,  235,   33,  234,  233,  232,  231,  228,  227,

      225,  224,  223,  222,   60,   27,   28,  221,   29,   30,
      220,  219,   31,   59,  217,   33,  216,  214,  212,  210,
      211,  210,  203,  202,  201,  199,   60,  105,  198,  105,
      105,  105,  105,  105,  105,  105,  106,  105,  105,  197,
      196,  195,  194,  193,  105,  192,  190,  189,  187,  185,
      181,  180,  179,  178,  176,  175,  173,  172,  171,  170,
      169,  168,  166,  165,  163,  161,  105,  105,  182,  160,
      182,  182,  182,  182,  182,  182,  182,  183,  182,  182,
      159,  158,  157,  156,  155,  182,  433,  153,  152,  149,
      148,  147,  146,  145,  144,  143,  116,  141,  140,  138,

      136,  134,  135,  134,  133,  132,  131,  182,  182,   26,
       26,   26,   26,   26,   26,   26,   26,   67,  130,   67,
       67,   67,   73,  128,   73,   73,   75,  127,   75,   77,
      124,   77,   80,  123,   80,   80,   83,  122,   83,   95,
       95,  100,  100,  100,  100,  100,  107,  121,  107,  107,
      107,  107,  107,  107,  109,  120,  109,  111,  119,  111,
      115,   88,  115,  125,  125,  126,  126,  129,  118,  129,
      137,   86,  137,  139,  117,  139,  142,  116,  142,  150,
      150,  151,  151,  154,  114,  154,   79,  154,  162,  112,
      162,  164,  110,  164,  167,  108,  167,  174,  174,  177,

      433,  177,  182,  104,  182,  182,  182,  182,  182,  182,
      184,  103,  184,  184,  184,  184,  184,  184,  186,  102,
      186,  188,  101,  188,  191,   94,  191,  200,   93,  200,
      213,   92,  213,  215,   91,  215,  218,   90,  218,  226,
       89,  226,  239,   88,  239,  241,   87,  241,  244,   86,
      244,  252,   85,  252,  264,   84,  264,  266,   82,  266,
      269,   81,  269,  277,   79,  277,  290,   78,  290,  291,
       76,  291,  116,   74,  116,   72,   71,   70,   69,   68,
       63,   62,   61,  433,   25,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433
    } ;

static yyconst flex_int16_t yy_chk[727] =
    {   0,
        0,    1,    1,    0,    1,    1,   34,    0,    1,    1,
       34,    1,    1,    1,   80,   80,    1,    0,    1,    1,
        1,    1,    1,    1,    2,    2,   32,    2,    2,   32,
       32,    2,    2,    0,    2,    2,    2,  281,  281,    2,
      431,    2,    2,    2,    2,    2,    2,    3,    3,  254,
        3,    3,   67,   67,    3,    3,   67,    3,   65,   65,
      429,   65,   65,  428,  427,  204,  254,  426,    3,    4,
        4,  425,    4,    4,  423,  422,    4,    4,  204,    4,
      420,    5,    5,  418,    5,    5,  416,  415,    5,  414,
        4,    5,    6,    6,  413,    6,    6,  411,  410,    6,

      407,  406,    6,    7,  405,  404,    7,    7,  403,  402,
        7,  401,    7,    7,    7,    7,    7,    7,    9,  400,
      399,    9,    9,  398,  397,  396,  395,    9,    9,    9,
        9,    9,    9,   11,   11,  394,   11,   11,  393,  392,
       11,   11,  390,   11,  389,  388,  387,  386,  181,  385,
      383,  181,  382,  381,   11,   12,   12,  181,   12,   12,
      181,  380,   12,   12,  181,   12,  379,  181,  378,  377,
      376,  375,  374,  373,  372,  371,   12,   13,   13,  369,
      368,  367,  366,  365,  363,   13,  362,  361,   13,   13,
      360,  359,  358,  357,   13,   13,   13,   13,   13,   13,

      356,  355,  354,  353,  352,  351,   13,   15,   15,  350,
       15,   15,  349,  348,   15,   15,  347,   15,  345,  344,
      342,  341,  340,  339,  338,  337,  336,  335,   15,   16,
       16,  334,   16,   16,  333,  332,   16,   16,  331,   16,
      330,  329,  328,  327,  326,  325,  324,  323,  322,  321,
       16,   17,   17,  320,   17,   17,  319,  318,   17,   17,
      317,   17,  316,  315,  314,  313,  312,  311,  310,  309,
      308,  306,   17,   18,   18,  305,   18,   18,  304,  303,
       18,   18,  302,   18,  301,  299,  298,  297,  296,  295,
      294,  293,  292,  289,   18,   19,   19,  288,   19,   19,

      286,  285,   19,   19,  284,   19,  283,  282,  280,  279,
      278,  274,  272,  271,  270,  268,   19,   20,   20,  267,
       20,   20,  263,  262,   20,   20,  261,   20,  260,  259,
      258,  257,  256,  255,  253,  251,  250,  249,   20,   21,
       21,  248,   21,   21,  247,  246,   21,   21,  245,   21,
      243,  242,  240,  238,  237,  236,  235,  234,  233,  232,
       21,   22,   22,  231,   22,   22,  230,  229,   22,   22,
      228,   22,  225,  224,  223,  222,  221,  220,  219,  217,
      216,  214,   22,   23,   23,  212,   23,   23,  211,  210,
       23,   23,  209,   23,  208,  207,  206,  205,  203,  201,

      199,  198,  197,  196,   23,   24,   24,  195,   24,   24,
      193,  192,   24,   24,  190,   24,  189,  187,  185,  184,
      183,  182,  180,  179,  178,  176,   24,   72,  175,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,  173,
      172,  171,  170,  169,   72,  168,  166,  165,  163,  161,
      158,  157,  156,  155,  153,  152,  149,  148,  146,  145,
      144,  143,  141,  140,  138,  136,   72,   72,  160,  135,
      160,  160,  160,  160,  160,  160,  160,  160,  160,  160,
      134,  133,  132,  131,  130,  160,  129,  128,  127,  124,
      123,  122,  121,  120,  119,  118,  117,  114,  112,  110,

      108,  107,  106,  105,  104,  103,  101,  160,  160,  434,
      434,  434,  434,  434,  434,  434,  434,  435,   99,  435,
      435,  435,  436,   98,  436,  436,  437,   97,  437,  438,
       94,  438,  439,   93,  439,  439,  440,   92,  440,  441,
      441,  442,  442,  442,  442,  442,  443,   91,  443,  443,
      443,  443,  443,  443,  444,   90,  444,  445,   89,  445,
      446,   88,  446,  447,  447,  448,  448,  449,   87,  449,
      450,   86,  450,  451,   85,  451,  452,   84,  452,  453,
      453,  454,  454,  455,   81,  455,   79,  455,  456,   78,
      456,  457,   76,  457,  458,   74,  458,  459,  459,  460,

       73,  460,  461,   71,  461,  461,  461,  461,  461,  461,
      462,   69,  462,  462,  462,  462,  462,  462,  463,   68,
      463,  464,   66,  464,  465,   60,  465,  466,   58,  466,
      467,   57,  467,  468,   56,  468,  469,   55,  469,  470,
       54,  470,  471,   53,  471,  472,   52,  472,  473,   51,
      473,  474,   50,  474,  475,   49,  475,  476,   47,  476,
      477,   45,  477,  478,   44,  478,  479,   43,  479,  480,
       41,  480,  481,   39,  481,   38,   37,   36,   35,   33,
       31,   29,   28,   25,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,

      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433,  433,  433,  433,  433,
      433,  433,  433,  433,  433,  433
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.lex"
#line 2 "scanner.lex"
#include <iostream>
#include <boost/date_time/posix_time/posix_time.hpp>
#include <vector>
#include <utility>
#include <cctype>
#include <algorithm>
#include <map>
#include <sstream>
#include <boost/date_time/gregorian/greg_month.hpp>

using namespace std;
using namespace boost::posix_time;
using namespace boost::gregorian;

string Tid; string Date; string Time; string HexId; 
char *pch;
unsigned int bats_counter = 0;

pair<string,string> entry_pair;
extern vector < pair<string,string> >  box_entries; 
extern string Year; //the year of the analysis
extern map<string,string> monaten; //maps months to their numerical value

extern map<string,ptime> box_occupation; //maps box names to their dates of occupation
					 //if a box has not been occupied, this date
					 //is set to not_a_date_time

/*stores the box programming: box_name->vector of bats programmed for this box*/
extern map<string,vector<string> > box_programming; 

//pair<string,ptime> box_occupation_entry;
string box_name, box_date,current_programmed_box;

extern map<string,unsigned,bool(*)(string,string)> bats_map;
//extern vector<string> bats_vector;
extern vector<string> transponders_vector;
extern time_duration knowledge_delay;
extern time_duration lf_delay;
extern string occupation_deadline;
extern string Year;
extern bool create_sqlitedb;
int comment_caller;











#line 826 "standard.yy.c"

#define INITIAL 0
#define BOX_OCCUPATION 1
#define COMMENT 2
#define BATS 3
#define TRANSPONDERS 4
#define BOX_PROGRAMMING 5
#define INSIDE_BOX_PROGRAMMING 6
#define BATUPDATE 7
#define LFDELAY 8
#define OCCUPATIONDEADLINE 9
#define YEAR 10
#define EXPORTDATABASE 11

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 60 "scanner.lex"

#line 1026 "standard.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 434 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 685 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 61 "scanner.lex"
BEGIN(EXPORTDATABASE);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 62 "scanner.lex"
BEGIN(YEAR);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 63 "scanner.lex"
BEGIN(OCCUPATIONDEADLINE);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 64 "scanner.lex"
BEGIN(LFDELAY);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 65 "scanner.lex"
BEGIN(BATUPDATE);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 66 "scanner.lex"
BEGIN(TRANSPONDERS);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 67 "scanner.lex"
BEGIN(BATS);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 68 "scanner.lex"
BEGIN(BOX_OCCUPATION);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "scanner.lex"
{current_programmed_box="";BEGIN(BOX_PROGRAMMING);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 70 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 71 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 72 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 73 "scanner.lex"
BEGIN(INITIAL);  
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 74 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 75 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 76 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 77 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 78 "scanner.lex"
BEGIN(INITIAL);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 80 "scanner.lex"
{
  string ss;
  pch=strtok(yytext,".");
  ss=pch;
  if (ss == "0") create_sqlitedb=false;
  else if (ss == "1") create_sqlitedb=true;
  else {
    printf("Error: Unrecognized value for exportdatabase in config file\n");
    exit(1);
  }
}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 92 "scanner.lex"
{
  pch=strtok(yytext,":");
  current_programmed_box = pch;
  BEGIN(INSIDE_BOX_PROGRAMMING);
}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 98 "scanner.lex"
{
  pch=strtok(yytext,".");
  string current_programmed_bat = pch;
  if (current_programmed_box == "") {
    printf("Error: Something went wrong while processing the box programming from the config file\n");
    exit(1);
  }  
  vector<string> &ref = box_programming[current_programmed_box];
  ref.push_back(current_programmed_bat);  
}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 109 "scanner.lex"
{
  pch=strtok(yytext,".");
  Year = pch;
}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 114 "scanner.lex"
{
  pch=strtok(yytext,".");
  occupation_deadline = pch;
}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 119 "scanner.lex"
{
  int digit;
  stringstream ss;
  pch = strtok(yytext,".");
  //printf("%s\n",pch);
  ss<<pch; ss>>digit;
  lf_delay = minutes(digit);
}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 129 "scanner.lex"
{
  int digit;
  stringstream ss;
  pch = strtok(yytext,".");
  //printf("%s\n",pch);
  ss<<pch; ss>>digit;
  knowledge_delay = minutes(digit);
}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 138 "scanner.lex"
{  
  string transponders_hexid;
  pch = strtok(yytext,".");
  transponders_hexid = pch;
  transponders_vector.push_back(transponders_hexid);
}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 146 "scanner.lex"
{  
  string bat_hexid;
  pch = strtok(yytext,".");
  bat_hexid = pch;
  bats_map[bat_hexid] = bats_counter++;
  //bats_vector.push_back(bat_hexid);
}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 155 "scanner.lex"
{
  
  pch = strtok(yytext,".");
  box_name = pch;
  //printf("box: %s\n",box_name.c_str());
}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 162 "scanner.lex"
{
  string local_day, local_month, local_year;
  pch = strtok(yytext,".");
  local_day = pch;
  pch = strtok(NULL,".");
  local_month = pch;
  pch = strtok(NULL,".");
  local_year = pch;
  box_date = local_year+local_month+local_day+"T"+occupation_deadline; 
  //printf("Time: %s\n",box_date.c_str());
  ptime occupation_time(from_iso_string(box_date));
  //printf("Time: %s\n",to_simple_string(occupation_time).c_str());
  box_occupation[box_name] =  occupation_time;
}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 178 "scanner.lex"
{
  string local_month, local_day, local_year;  
  pch = strtok(yytext,"-");
  local_year = pch;
  pch = strtok(NULL,"-");
  local_month = pch;
  pch = strtok(NULL,"-");
  local_day = pch;  
  Date = local_year + local_month + local_day;//20020131
  //printf("Year: %s ",Date.c_str());  

}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 191 "scanner.lex"
{
  string local_month, local_day, local_year;
  
  pch = strtok(yytext,".");
  local_day = pch;
  pch = strtok(NULL,".");
  local_month = pch;
  pch = strtok(NULL,".");
  local_year = pch;
  
  Date = local_year + local_month + local_day;//20020131
  //printf("Year: %s ",Date.c_str());
}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 205 "scanner.lex"
{
  string local_month, local_day="0";
  stringstream ss;
  pch = strtok(yytext,"-");
  local_day += pch;
  pch = strtok(NULL,"-");
  local_month = pch;
  transform(local_month.begin(), local_month.end(),local_month.begin(),::toupper);
  
  ss<<Year<<monaten[local_month]<<local_day;    
  Date = ss.str(); //20080131
  //printf("A date: %s ",Date.c_str());
}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 220 "scanner.lex"
{
  string local_month, local_day;
  stringstream ss;
  
  pch = strtok(yytext,"-");
  local_day = pch;
  pch = strtok(NULL,"-");
  local_month = pch;
  transform(local_month.begin(), local_month.end(),local_month.begin(),::toupper);
  
  ss<<Year<<monaten[local_month]<<local_day;    
  Date = ss.str(); //20080131
  //printf("A date: %s ",Date.c_str());
}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 237 "scanner.lex"
{
  string local_month, local_day;
  
  pch = strtok(yytext,".");
  local_day = pch;
  pch = strtok(NULL,".");
  local_month = pch;

  Date = Year + local_month + local_day; //20080131
  //printf("A date: %s ",yytext);
}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 252 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 253 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 254 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 255 "scanner.lex"
/*ignore this token*/
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 257 "scanner.lex"
{
  Time="0";
  pch = strtok(yytext,":");
  Time = Time + pch;
  pch = strtok(NULL,":");
  Time += pch;
  pch = strtok(NULL,":");
  Time += pch;

  Date += "T" + Time; //20020131T235959
  //printf("Time: %s\n",Date.c_str());
  
  if (!HexId.empty()) { //Trovan Unique files
    //HexId should've been already scanned
    if (HexId == "000697B587") //this bat was mistakenly recorded in the transponders
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }

}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 284 "scanner.lex"
{
  pch = strtok(yytext,":");
  Time = pch;
  pch = strtok(NULL,":");
  Time += pch;
  pch = strtok(NULL,":");
  Time += pch;

  Date += "T" + Time; //20020131T235959
  //printf("Time: %s\n",Date.c_str());
  
  if (!HexId.empty()) { //Trovan Unique files
    //HexId should've been already scanned
    if (HexId == "000697B587") //this bat was mistakenly recorded in the transponders
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }

}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 309 "scanner.lex"
{
  HexId = yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);
  //cout<<HexId<<endl;
  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 326 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "0";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 346 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "00";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 366 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "000";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 384 "scanner.lex"
{//because the stupid .txt file for 2007 sometimes clipps the leading zeros :-(
  HexId = "0000";
  HexId += yytext;
  transform( HexId.begin(), HexId.end(),HexId.begin(),::toupper);

  if (!Date.empty()) { //non-Trovan unique files
    if (HexId == "000697B587")
      HexId = "000697B597";
    entry_pair.first = HexId;
    entry_pair.second = Date;
    box_entries.push_back(entry_pair);
    Date = "";
    Time = "";
    HexId = "";
  }
  //printf("TID: %s\n",yytext);
}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 406 "scanner.lex"
/* ignore this token */
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 408 "scanner.lex"
{
  box_entries.pop_back();
  Date = "";
  Time = "";
  HexId = "";
}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 415 "scanner.lex"
{
comment_caller = YY_START;
BEGIN(COMMENT);
}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 419 "scanner.lex"
BEGIN(comment_caller);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 422 "scanner.lex"
//{printf("%s",yytext);}/* ignore this token in any start condition*/
	YY_BREAK
case 51:
/* rule 51 can match eol */
YY_RULE_SETUP
#line 424 "scanner.lex"
{BEGIN(BOX_PROGRAMMING);}
	YY_BREAK
case 52:
/* rule 52 can match eol */
YY_RULE_SETUP
#line 426 "scanner.lex"
//{printf("%s",yytext);}/*ignore this token in any start condition*/
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 428 "scanner.lex"
ECHO;
	YY_BREAK
#line 1640 "standard.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(BOX_OCCUPATION):
case YY_STATE_EOF(COMMENT):
case YY_STATE_EOF(BATS):
case YY_STATE_EOF(TRANSPONDERS):
case YY_STATE_EOF(BOX_PROGRAMMING):
case YY_STATE_EOF(INSIDE_BOX_PROGRAMMING):
case YY_STATE_EOF(BATUPDATE):
case YY_STATE_EOF(LFDELAY):
case YY_STATE_EOF(OCCUPATIONDEADLINE):
case YY_STATE_EOF(YEAR):
case YY_STATE_EOF(EXPORTDATABASE):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 434 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 434 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 433);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 428 "scanner.lex"





